name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  deploy:
    name: release   
    runs-on:
      group: npm-deploy
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: Setup Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
     
      - name: Release
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional
        run: yarn g:release
